### PR TITLE
Add elastic deformation in 2D and 3D

### PR DESCRIPTION
**Pull request by michaeld123**
As discussed on gitter, I've had a shot at elastic deformation. I have limited example data to test it on so please let me know if it needs changes to make it more versatile.

I've put some examples here:
https://github.com/michaeld123/tests/blob/master/02_Augmentation_Tests_Elastic_Deformation_3D.ipynb

It has 4 cases, single/multiple channel 2D and 3D. Are all these needed? Or can we assume always multichannel?

Also, I have chosen to make the z deformation proportional to the xy deformation. Is this valid?
It is straight forward to add more variables to the function so that these can be tuned separately.

Thanks!

### CODE REVIEW

**Comment by pawni** [comment]
Thanks for that contribution!

We had a look through the code and think the functionality looks good - however, we would rather want the function to take lists for both `alpha` and `sigma` and get rid of `zratio`. Then every dimension is treated the same way as there is no preference for a specific axis. Those lists will also give you the dimensionality of the image and infer whether channels are present or not. So it should be possible to build this function to work on n-D arrays with or without channels.

Could you make those changes?

Thanks!

**Comment by michaeld123** [comment]
Sure no problem - it's a good idea and should be a simple change. Just to clarify it's either 2D or 3D right? So alphavec2d = [ alpha_0 , alpha_1 ] or alphavec3d = [ alpha_0 , alpha_1, alpha_2 ]?

I'm on holiday at the moment, so I'll make the changes next week when I get back.

Thanks for the feedback!

**Comment by pawni** [comment]
In my opinion we shouldn't confine this to 2D or 3D as it's simply extensible from 1D to n-D with `alpha = [a_0 ... a_n]` and `sigma = [sigma_0 ... sigma_n]`.

Enjoy your holiday. We're looking forward to the changes.

**Comment by michaeld123** [comment]
I've completely rewritten it to work on n-D. I've put up some examples here:
https://github.com/michaeld123/tests/blob/master/03_Augmentation_Tests_Elastic_Deformation_ND.ipynb

Let me know what you think.

**Comment by pawni** [comment]
Looks good. Sorry for taking that long to check it.

**Pull request merged**
