### PR TITLE
Add docker setup

### PR DESCRIPTION
**Pull request by mdjaere**
Hi everyone,

As discussed on https://gitter.im/DLTK/DLTK: Here's a simple docker implementation built on tensorflow's image from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker. It enables DLTK to be available in a pre-built, sandboxed and easy to use environment.

Let me know what you think.

Many thanks,
Martin DJ

### CODE REVIEW

**Comment by pawni** [comment]
Hi Martin,

thanks for your PR! I looked through it and it sounds quite good already. Could you please squash you commits? Also I think it'd be good to autobuild the image and host it under DLTK. For that I already pushed to https://hub.docker.com/r/dltk/dltk/ . Could you change that in the readme and also add it to the changelog and general readme (as well as your name as contributor)?

Thanks!

**Comment by mdjaere** [comment]
Hi @pawni,

Thanks for the feedback! I have now added most of your suggestions and a few other amendments. Apologies for the many commits, I am not sure how best to squash them.

I have not attempted to implement automatic image build and push to registry since I assume it needs secrets from Travis, but I would be happy to help if needed. 

NB. Be aware that the docker build will pull the source from the github master branch, so make sure the repo is updated before starting.

Many thanks,
Martin

**Comment by mdjaere** [comment]
Hi @pawni,

One thing I'm still unsure about is persistence of the DLTK example data folder (70+GB). The challange is that the download scripts (dl scripts) are located in the `/data` folder, but it's also the download destination. Therefore, if you mount an empty local folder to `/data`, to be used as persistent download destination, it will naturally appear empty inside of the container, with none of the dl scripts available. 

There are multiple ways to solve this, but the way I left it [now](https://github.com/mdjaere/DLTK/blob/add-docker/tools/docker/Dockerfile) is by copying the dl scripts into the mounted folder just after container boot. This works well, but you _will_ end up with a few extra files on your local drive if you choose to mount a folder to `/data`, even without opening the tutorials. On the other hand, if you mount a pre-downloaded data folder, no files will be overwritten and work well with the tutorials.

This works OK, but I'm sure it can be solved more elegantly.

Other solutions may be:
- Have separate download destination and script locations.
- Copy the dl scripts from the repo source present in the image, to the `/data` folder as part of the tutorial
- Have the dl-scripts be part of the module e.g. `from dltk.examples.tutorials.MRBrainS13DataNi import input_data` (Inspired by the tf mnist tutorial - probably my favorite)

Let me know if you have any thoughts on this.

PS. I realise that this PR has become untidy by many commits. I would be very happy to close this pull request, and open new and improved PR with a single commit.

**Comment by mdjaere** [comment]
Hi,

I'll close this now to make another attempt soon. 
Please let me know if you have any thoughts on requirements for dltk in docker.

Best wishes,
Martin

**Pull request closed without merging**
