### PR TITLE
Minor tweaks and multi-GPU example

### PR DESCRIPTION
**Pull request by ericspod**
I tweaked the output of a few places to use warnings instead of print() and added a toy multi-GPU example. I was working on getting my code going on multiple GPUs and had adapted the toy example as a test, so it might be instructional to others.

### CODE REVIEW

**Comment by pawni** [comment]
Thanks a lot for adding that example (as well as for the small tweaks)
Does your run learn something reasonable? I was running the code and only got quite bad segmentations:
segmentation_example
How does yours look?

**Comment by ericspod** [comment]
It had been working for me on another computer but this was using a previous version of DLTK. I was able to reproduce your issue on other computers and it took a while to figure out the differences. At some point the definition of dice_loss() has been changed to no longer function correctly with one class. See the previous definition here: https://github.com/DLTK/DLTK/blob/5f78c9ce5318819dfe1639f8255df3d95d651e86/dltk/core/modules/losses.py

If I copy-paste that version of dice_loss() into either toy examples they work again. I guess the change got lost in someone's commit that was slightly outdated?

**Comment by pawni** [comment]
Oh alright! Sorry about that - I must have missed that when merging some things in recently. I'll merge your PR and fix the issue ASAP.

Thanks for spotting this :)

**Comment by ericspod** [comment]
No worries! I had made up the example as a test so it's doing it's job.

**Pull request merged**
